SECActivityBookingCore/Controllers/ParticipantsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using NewApplication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace NewApplication.Controllers
{
    public class ParticipantsController : Controller
    {
        private DBModelContainer db = new DBModelContainer();
        /*
        // GET: Participants
        public ActionResult Index()
        {
            var participants = db.Participants.Include(p => p.Club);
            return View(participants.ToList());
        }
        */
        // GET: Participants/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new StatusCodeResult((int) HttpStatusCode.BadRequest);
            }
            Participant participant = db.Participants.Find(id);
            if (participant == null)
            {
                return NotFound();
            }
            int clubId = participant.Club.ClubId;
            var adminSession = HttpContext.Session.GetString("VerifiedActiv") as string;
            if (HttpContext.Session.GetString("VerifiedClub") != null || adminSession == true.ToString())
            {
                var sessionClub = HttpContext.Session.GetString("VerifiedClub") as string;
                if (sessionClub == clubId.ToString() || adminSession == true.ToString())
                {
                    
                    return View(participant);
                }
            }
            return RedirectToAction("clubPassGet", "Clubs", new { id = clubId }) ;
        }

        public PartialViewResult Sessions(int? id)
        {
            ViewBag.ParticipantId = id;
            List<SessionGroup> sessionGroups = db.SessionGroups.ToList();
            return PartialView(sessionGroups);
        }

        public PartialViewResult SessionActivities(int? sessionGroupId, int participantId)
        {
            ViewBag.ParticipantId = participantId;
            Participant participant = db.Participants.Find(participantId);
            ViewBag.Participant = participant;
            int ageGroupId = participant.AgeGroup_AgeGroupId;
            List<Session> sessions = db.Sessions.Where(session => session.SessionGroupSessionGroupId == sessionGroupId).ToList();
            List<Session> unbookedSession = sessions.Where(session => !session.Participants.Contains(participant)).ToList();
            List<Session> validSessions = sessions.Where(session => session.Participants.Contains(participant)).ToList();
            if(validSessions.Count() > 0)
            {
                List<Session> newSessions = validSessions.Where(session => session.Activity.AgeGroupAgeGroupId == ageGroupId).ToList();
                IEnumerable<Session> allParticipantSessions = participant.Sessions;
                return PartialView(newSessions);
            }
            else
            {
                List<Session> testSession = db.GetParticipantSessions(participantId).Where(session => session.SessionGroupSessionGroupId == sessionGroupId).ToList();
                List<Session> newSessions = testSession.Where(session => session.Activity.AgeGroupAgeGroupId == ageGroupId).ToList();
                IEnumerable<Session> allParticipantSessions = participant.Sessions;
                return PartialView(newSessions);
            }
            
        }
        
        public bool AddParticpant(int sessionId, int participantId)
        {
            Session session = db.Sessions.Find(sessionId);
            Participant participant = db.Participants.Find(participantId);
            if (!session.Participants.Contains(participant))
            {
                session.Participants.Add(participant);
            }
            db.Entry(session).State = EntityState.Modified;
            db.SaveChanges();
            return true;
        }

        public bool RemoveParticipant(int sessionId, int participantId)
        {
            Session session = db.Sessions.Find(sessionId);
            Participant participant = db.Participants.Find(participantId);
            if (session.Participants.Contains(participant))
            {
                session.Participants.Remove(participant);
            }
            db.Entry(session).State = EntityState.Modified;
            db.SaveChanges();
            return true;
        }
        /*
        // GET: Participants/Create
        public ActionResult Create()
        {
            ViewBag.ClubClubId = new SelectList(db.Clubs, "ClubId", "ClubName");
            return View();
        }

        // POST: Participants/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ParticipantId,ClubClubId,ParticipantFirstName")] Participant participant)
        {
            if (ModelState.IsValid)
            {
                db.Participants.Add(participant);
                db.SaveChanges();
                return RedirectToAction("Details", "Clubs",  new { id = participant.ClubClubId });
            }

            ViewBag.ClubClubId = new SelectList(db.Clubs, "ClubId", "ClubName", participant.ClubClubId);
            Club club = db.Clubs.Find(participant.ClubClubId);
            return View("Details", "Clubs", club);
        }
*/
        // GET: Participants/Edit/5
        public ActionResult Edit(int? id, int clubId)
        {
            if (id == null)
            {
                return new StatusCodeResult((int) HttpStatusCode.BadRequest);
            }
            Participant participant = db.Participants.Find(id);
            if (participant == null)
            {
                return NotFound();
            }
            ViewBag.ClubClubId = clubId;
            ViewBag.AgeGroup_AgeGroupId = new SelectList(db.AgeGroups, "AgeGroupId", "AgeGroupName", participant.AgeGroup_AgeGroupId);
            return View(participant);
        }

        // POST: Participants/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind("ParticipantId,ClubClubId,ParticipantFirstName,AgeGroup_AgeGroupId")] Participant participant)
        {
            if (ModelState.IsValid)
            {
                db.Entry(participant).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", "Clubs", new { id = participant.ClubClubId });
            }
            ViewBag.AgeGroup_AgeGroupId = new SelectList(db.AgeGroups, "AgeGroupId", "AgeGroupName", participant.AgeGroup_AgeGroupId);
            Club club = db.Clubs.Find(participant.ClubClubId);
            return RedirectToAction("Details", "Clubs", new { id = participant.ClubClubId });
        }

        public ActionResult ParticipantSessions(int? id)
        {
            if (id == null)
            {
                return new StatusCodeResult((int) HttpStatusCode.BadRequest);
            }
            Participant participant = db.Participants.Find(id);
            if (participant == null)
            {
                return NotFound();
            }
            return View(participant);
        }
        /*
        // GET: Participants/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Participant participant = db.Participants.Find(id);
            if (participant == null)
            {
                return HttpNotFound();
            }
            return View(participant);
        }

        // POST: Participants/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Participant participant = db.Participants.Find(id);
            db.Participants.Remove(participant);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        */

    }
}

SECActivityBookingCore/Controllers/SessionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using NewApplication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace NewApplication.Controllers
{
    public class SessionsController : Controller
    {
        private DBModelContainer db = new DBModelContainer();

        // GET: Sessions
        /*
        public ActionResult Index()
        {
            var sessions = db.Sessions.Include(s => s.Activity).Include(s => s.SessionGroup);
            return View(sessions.ToList());
        }

        // GET: Sessions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Session session = db.Sessions.Find(id);
            if (session == null)
            {
                return HttpNotFound();
            }
            return View(session);
        }
        /*
        // GET: Sessions/Create
        public ActionResult Create()
        {
            ViewBag.ActivityActivityId = new SelectList(db.Activities, "ActivityId", "ActivityName");
            ViewBag.SessionGroupSessionGroupId = new SelectList(db.SessionGroups, "SessionGroupId", "SessionName");
            return View();
        }

        // POST: Sessions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SessionId,ZoneZoneId,SessionGroupSessionGroupId,ActivityActivityId,SessionName")] Session session)
        {
            if (ModelState.IsValid)
            {
                db.Sessions.Add(session);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ActivityActivityId = new SelectList(db.Activities, "ActivityId", "ActivityName", session.ActivityActivityId);
            ViewBag.SessionGroupSessionGroupId = new SelectList(db.SessionGroups, "SessionGroupId", "SessionName", session.SessionGroupSessionGroupId);
            return View(session);
        }
       
        // GET: Sessions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Session session = db.Sessions.Find(id);
            if (session == null)
            {
                return HttpNotFound();
            }
            ViewBag.ActivityActivityId = new SelectList(db.Activities, "ActivityId", "ActivityName", session.ActivityActivityId);
            ViewBag.SessionGroupSessionGroupId = new SelectList(db.SessionGroups, "SessionGroupId", "SessionName", session.SessionGroupSessionGroupId);
            return View(session);
        }

        // POST: Sessions/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "SessionId,ZoneZoneId,SessionGroupSessionGroupId,ActivityActivityId,SessionName")] Session session)
        {
            if (ModelState.IsValid)
            {
                db.Entry(session).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ActivityActivityId = new SelectList(db.Activities, "ActivityId", "ActivityName", session.ActivityActivityId);
            ViewBag.SessionGroupSessionGroupId = new SelectList(db.SessionGroups, "SessionGroupId", "SessionName", session.SessionGroupSessionGroupId);
            return View(session);
        }

        // GET: Sessions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Session session = db.Sessions.Find(id);
            if (session == null)
            {
                return HttpNotFound();
            }
            return View(session);
        }

        // POST: Sessions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Session session = db.Sessions.Find(id);
            db.Sessions.Remove(session);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        */
    }
}

SECActivityBookingCore/Views/Participants/Details.cshtml
@model NewApplication.Participant

@{
    ViewBag.Title = "Details";
}

<h2>@Model.ParticipantFirstName</h2>

<div>
    <h4>@Model.Club.ClubName</h4>
    <h5>@Model.AgeGroup.AgeGroupName</h5>
    @Html.ActionLink("Back to Club", "Details", "Clubs", new { id = Model.Club.ClubId }, htmlAttributes: new { @class = "btn btn-default" })


    <div id="sesssionsView">
        @Html.RenderAction("Sessions", new { id = Model.ParticipantId })
    </div>

</div>
<hr />




<script type="text/javascript">
        function addParticipant(participantId, sessionId) {
            console.log("Run Button");
            console.log(participantId, sessionId);
            $.ajax({
                type: "POST",
                data: {
                    sessionId: sessionId, participantId: participantId
                },
            url: "@Url.Action("AddParticpant", "Participants")",
                success: function (result) {
                    console.log(result);
                    $("#sesssionsView").load("@Url.Action("Sessions", new { id = Model.ParticipantId })");
                    alert("Participant Added Successfully");
                },
                error: function (result) {
                    console.log(result);
                    $("#sesssionsView").load("@Url.Action("Sessions", new { id = Model.ParticipantId })");
                    alert("An Error occured adding participant, please contact us to correct this");
                }
            });
    }

            function removeParticipant(participantId, sessionId) {
            console.log("Run Button");
            console.log(participantId, sessionId);
            $.ajax({
                type: "POST",
                data: {
                    sessionId: sessionId, participantId: participantId
                },
            url: "@Url.Action("RemoveParticipant", "Participants")",
                success: function (result) {
                    console.log(result);
                    $("#sesssionsView").load("@Url.Action("Sessions", new { id = Model.ParticipantId })");
                    alert("Participant Removed Successfully");
                },
                error: function (result) {
                    console.log(result);
                    $("#sesssionsView").load("@Url.Action("Sessions", new { id = Model.ParticipantId })");
                    alert("An Error occured removing participant, please contact us to correct this");
                }
            });
        }


</script>

SECActivityBookingCore/Views/Participants/Edit.cshtml
@model NewApplication.Participant

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Participant</h4>
    @Html.ActionLink("Back to Club", "Details", "Clubs", new { id = Model.Club.ClubId }, htmlAttributes: new { @class = "btn btn-default" })
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ParticipantId)
    @Html.HiddenFor(model => model.ClubClubId, htmlAttributes: new { @Value = ViewBag.ClubClubId })
    @*
        <div class="form-group">
            @Html.LabelFor(model => model.ClubClubId, "ClubClubId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ClubClubId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ClubClubId, "", new { @class = "text-danger" })
            </div>
        </div>
    *@
    <div class="form-group">
        @Html.LabelFor(model => model.AgeGroup_AgeGroupId, "AgeGroup_AgeGroupId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("AgeGroup_AgeGroupId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.AgeGroup_AgeGroupId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ParticipantFirstName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ParticipantFirstName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ParticipantFirstName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-success" />
        </div>
    </div>
</div>
}


@section Scripts {
    @*@Scripts.Render("~/bundles/jqueryval")*@
}

SECActivityBookingCore/Views/Participants/ParticipantSessions.cshtml
@model NewApplication.Participant

@{
    ViewBag.Title = "ParticipantSessions";
}

<h2>@Model.ParticipantFirstName</h2>

<div>
    <h4>@Model.Club.ClubName</h4>
    <h5>Particpant Sessions</h5>
    @Html.ActionLink("Back to Club", "Details", "Clubs", new { id = Model.Club.ClubId }, htmlAttributes: new { @class = "btn btn-default" })
    <hr />
    <table class="table display">
        <thead>
            <tr>
                <th>Activity Name</th>
                <th>Session Name</th>
                <th>Session Zone</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Sessions)
            {
                <tr>
                    <td>@item.Activity.ActivityName</td>
                    <td>@item.SessionGroup.SessionName</td>
                    <td>@item.Activity.Zone.ZoneName</td>
                </tr>
            }
        </tbody>
    </table>
</div>

SECActivityBookingCore/Views/Participants/SessionActivities.cshtml
@model IEnumerable<NewApplication.Session>



<table class="table_id display">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Activity.Zone.ZoneName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Activity.ActivityName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SessionGroup.SessionName)
            </th>
            <th>
                Places Remaining
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>

            <td>
                @Html.DisplayFor(modelItem => item.Activity.Zone.ZoneName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Activity.ActivityName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SessionGroup.SessionName)
            </td>
            <td>
                @(15-item.Participants.Count())
            </td>

            <td>

                @if (item.Participants.Contains(ViewBag.Participant))
                {
                    <button type="button" class="btn btn-default" onclick="removeParticipant('@ViewBag.ParticipantId','@item.SessionId')">Remove from Session</button>
                }
                @if (!item.Participants.Contains(ViewBag.Participant))
                {
                    if (item.Participants.Count() < 15)
                    {
                        <button type="button" class="btn btn-default" onclick="addParticipant('@ViewBag.ParticipantId','@item.SessionId')">Add to Session</button>
                    }
                    else
                    {
                        <p>No Spaces on Session</p>
                    }
                }


            </td>
        </tr>
        }
    </tbody>
</table>

<script>
    $(document).ready(function () {
        $('.table_id').DataTable();
    });
</script>

SECActivityBookingCore/Views/Participants/Sessions.cshtml
@model IEnumerable<NewApplication.SessionGroup>


<table class="table">
@foreach (var item in Model) {
    <tr>
        <th>
            @Html.DisplayFor(modelItem => item.SessionName)
        </th>
    </tr>
    <tr>
        <td>
                @Html.RenderAction("SessionActivities", new { sessionGroupId = item.SessionGroupId, participantId = ViewBag.ParticipantId })
        </td>
    </tr>

}
</table>